# Site settings
title:          ochzhen
description:    "Personal blog"
url:            "https://ochzhen.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Alex Chzhen
  url:          https://github.com/ochzhen
  email:        oleksandr.chzhen@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
collections:
  posts:
    permalink: /blog/:title

paginate:  5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale