# Site settings
title:          ochzhen
description:    "Oleksandr (Alex) Chzhen's personal blog"
url:            "https://ochzhen.com"

# Google Analytics
google_analytics: G-H8YE31Q1NN

# Author
author:
  name:         Oleksandr Chzhen
  url:          https://github.com/ochzhen
  email:        oleksandr.chzhen@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
collections:
  posts:
    permalink:  /blog/:title
  projects:
    permalink:  /projects/:name
    output:     true

paginate:  5
paginate_path: "/blog/page:num"

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale